### ISSUE TITLE
Texto online explicando el trabajo

### ISSUE THREAD

**Issue by jgsogo** [jgsogo/muia-linkeddata#14]
Si alguien se anima a rellenar el "about" es más que bienvenido... se trataría de modificar este archivo

> muia-linkeddata/webapp/linkeddata/templates/linkeddata/about.html

y aparecería en la URL http://rafco.jgsogo.es/about/

**Comment by irenecordoba** [comment]
Que pena, yo pensaba que lo íbamos a dejar en tu servidor xD osea que cuando terminemos el proyecto esto se cierra?

**Comment by jgsogo** [comment]
A ver, se puede quedar ahí, a mí no me molesta, pero no me puedo comprometer a que esté online forever... y además, si lo dejamos ahí puesto, habría que plantearse en serio el tema de licencias.

**Comment by irenecordoba** [comment]
Ya... bueno al menos dejamos el proyecto de GitHub por si nos da por retomarlo o mejorarlo en el futuro :D que se ha quedado chulo.

Volviendo al issue, cuando me has dicho que use Sphinx, imagino que tenías en mente generar varias páginas en HTML, pero ¿es realmente necesario? ¿no podemos poner los apartados directamente en el about.html con headers y un índice al principio con links? ¿o qué tenías en mente?

**Comment by jgsogo** [comment]
A ver, a ver, mi idea era meter ahí cuatro líneas para explicar qué es por
si algún navegante pasa por ahí y después hacer el PDF por otro lado.

Sphinx no implica hacer varios HTML o uno solo... pero eso, que yo sólo lo
comentaba como una tecnología interesante. Que vaya a liderar esta parte
que elija qué y cómo. Yo estos días voy a tener q priorizar otras cosas, q
si no, no llego.

**Comment by irenecordoba** [comment]
Ok como yo estoy igual que tu e imagino que Alfonso también andará liado entonces hago yo el breve texto en el about.html y luego hacemos el pdf y listo. Crearé otro issue para la repartición del pdf.

**Comment by alfhonso** [comment]
Me parece bien.

**Comment by irenecordoba** [comment]
He subido el texto del about. Solamente quedaría rellenar los enlaces al documento de la ontología y al de Linked Data que hagamos. Si algo no os gusta cambiadlo, lo he hecho en plan visión general porque luego en los documentos ya damos muchísimo detalle.

**Comment by irenecordoba** [comment]
No se nos tiene que olvidar subir los pdfs de la ontología y de la aplicación cuando los tengamos y actualizar los enlaces del about.

**Comment by irenecordoba** [comment]
BUMP 

Creo que sigue faltando actualizar los enlaces del about, ya tenemos los pdf ^^

**Comment by jgsogo** [comment]
venga ahí d218dbf8e910595bf6b3ca1473bb2d3f85f02f1c
