### ISSUE TITLE
Texto online explicando la ontología

### ISSUE THREAD

**Issue by jgsogo** [jgsogo/muia-linkeddata#15]
Muchas ontologías tienen un HTML explicativo, la nuestra lo tendría aquí:

> muia-linkeddata/webapp/linkeddata/templates/linkeddata/ontology.html

y se accede a través de la URL http://rafco.jgsogo.es/ontology/ Si alguien se aburre mucho (pero mucho)...

**Comment by irenecordoba** [comment]
Yo esto, teniendo el texto del about y enlazado en esa misma página el pdf de la ontología, pasaría. Me lo plantearía ya si el día de mañana nos ponemos en serio y compramos el dominio rafco.es y miramos licencias xD Pero para lo que es esta práctica cerraría el issue, a no ser que @alfhonso quiera darle jajaja

**Comment by alfhonso** [comment]
Nada. Cerramos
