### ISSUE TITLE
Ingredient extraction from Recipes

### ISSUE THREAD

**Issue by alfhonso** [jgsogo/muia-linkeddata#17]
Script para match de ingredients en lista extraida de recipes finalizado. Se ejecuta:
    python manage.py match_ingredients ../data/rafco/

El archivo que toma de entrada debe llamarse recipes.txt. Genera como salida INGREDIENTS.txt

Pendiente:
1.- La entrada es de ingredientes, pero tiene que asociarse de alguna manera a cada receta.
2.- En la prueba se detectaron un 40% de ingredientes. Que pasa con el resto?
3.- El Script no debe acabar en la extracción. Quizás debería resultar en una carga en BBDD.

**Comment by jgsogo** [comment]
Voy a hacer una primera importación "masiva" de recetas a ver qué pasa... cogeré la línea 

> food = Food.objects.filter(Long_Desc__icontains=u'%s' %data[0]).first()

para utilizarla en el ```FoodManager::search```, así se hace en paralelo con la importación ;D

**Comment by jgsogo** [comment]
@alfhonso , propuesta para el matching de ingredientes: ee9cb385825955e99a41d51eece33cf59e79cb5d ;D

**Comment by alfhonso** [comment]
Cerramos esto
