### ISSUE TITLE
Future Work

### ISSUE THREAD

**Issue by irenecordoba** [jgsogo/muia-linkeddata#19]
Abro este issue para añadir las cosas que nos estamos saltando como sugiere @jgsogo en #9 y que se podrían poner en una versión futura.

* No hacemos ningún tipo de clasificación de los datos en las taxonomías que tenemos:
  * Los alimentos van directos a Food, aunque no es muy grave porque tienen el Langual y la clasificación que hay de Food es básicamente Langual prunned.
  * Los nutrientes (a Nutrient), los alérgenos (a Allergen), etc.
* Muchas propiedades inversas no las hemos puesto al hacer los R2RML.

**Comment by jgsogo** [comment]
* Decir que nos estamos saltando a la torera cualquier tipo de licencia (especialmente la de allrecipes.com que seguro que no nos dejarían hacer lo que hacemos)

 * La introducción de los ingredientes se hace a las bravas:
   * muchas cantidades no se corresponderán con las de las recetas
   * las unidades de medida.... tela.
   * y el matching de ingredientes puede resultar un show.

Ejemplo para que entendáis esto de las cantidades y unidades

> '2 1/2 teaspoon' ==> quantity=2 unit='teaspoon'   <-- se olvida del 1/2
'24 (2 ounces) chocolate tablet' ==> quantity=24 unit='tablet'
...

Vamos, que es un poco lotería. No obstante creo que tener los datos metidos en la DB es interesante, para hacer queries y que salgan cosas, poder navegar por la web,... luego si queremos hacer queries "BUENAS" podemos crear un par de recetas manualmente y trabajar sobre ellas.

**Comment by irenecordoba** [comment]
Las propiedades `unit` y `units` con dominios `IngredientWithAmount` y `Nutrient` se podrían juntar en una sola que fuese `unit` con dominio su `OR`. Lo puedo poner así fácilmente en la ontología y solamente habría que quitar una "s" de los R2RML. ¿Lo hago o lo dejo como está?

**Comment by irenecordoba** [comment]
* Algunos identificadores naturales en la base de datos MySQL no son PKs cuando deberían (y así también se podrían utilizar de forma natural en los R2RML para la generación de RDF). Es un future work de coherencia más que nada, porque @jgsogo lo solucionó poniendo un `_id`.

**Comment by irenecordoba** [comment]
* Cambiar `rafco:hasAuthor` por `foaf:isAuthor` o `schema:isAuthor` (TODO en recetas.ttl)
