### ISSUE TITLE
Main y Type en Nutrient y Allergen

### ISSUE THREAD

**Issue by irenecordoba** [jgsogo/muia-linkeddata#20]
@alfhonso en los datos de Nutrient aparecen dos campos `main` y `type`, que no tuvimos en cuenta en la ontología. ¿A qué tipo de datos deberían ir y qué significan? La misma pregunta aplicada a Allergen.

**Comment by alfhonso** [comment]
En ambos casos es la manera de recrear la taxonomía que definimos. En el caso de Nutrients:
      Main = Essential / Non Essential. Define si un nutrient es esencial o no.
      Type = Fat, Protein, VItamin, etc. Tipo de nutriente.

En el caso de Allergen:
      Main = Food / Non Food Allergen. Autoexplicativo.
      Type = Aero Plant, Food Animal, Food Plant, Food Fungus,... Tipo de alergeno.

Lo que sí ocurre en ambos casos y para ambos campos es que son completos. Es decir, cada nutriente o alergeno cae en un main o un type X. Salvo que empecemos con chuletones de extraterrestre, no habría nuevos Main o Types.

**Comment by irenecordoba** [comment]
Lo que no tengo muy claro es si se podría enlazar eso con la ontología de alguna forma directa. Ahora mismo se mete a pelo en una nueva clase `main` y `type`, pero claro esto no tiene mucho sentido si tenemos la ontología. ¿Future Work?

**Comment by alfhonso** [comment]
Main y Type son las que nos permiten clasificar en las subclass que sí definimos en la ontología. Es decir, no era propiedades inicialmente y su función no es para clases. Es para poder colocar cada instance en su subclass correspondiente. En cierto modo Main sobra, porque cada Type cae siempre en el mismo Main.

Dicho esto, aunque deberíamos mantener el Type de alguna manera, no es extrictamente necesario. Así que podemos poner en Future Work la definición de una propiedad isTypeOf.

Que te parece así?

**Comment by irenecordoba** [comment]
Tienes razón, cuando lo he escrito aquí me he equivocado, me refería a las **propiedades** `main` y `type`, que son lo que dices. Eso ya está tanto en los R2RML como en la ontología :)

Lo que sería para Future Work, que también está en el Final Report, es lo de colgar cada cosa de la taxonomía de forma *efectiva* (Nutrient, Allergen, Food, etc.). 

Así que perfecto!
