### ISSUE TITLE
IRIs a QUDT

### ISSUE THREAD

**Issue by irenecordoba** [jgsogo/muia-linkeddata#21]
Las IRIs que se generan en `recipe.tll` al hacer http://qudt.org/vocab/unit/{"Unit"} dan Error 404 al accederlas. Por ejemplo:

* http://qudt.org/vocab/unit/pound

¿Esto lo sabías cuando lo hiciste y simplemente no le damos importancia o es un error? He intentado corregirlo pero no encuentro equivalentes en [la ontología de QUDT](http://qudt.org/schema/qudt) cosas como `VolumeUnit`.

**Comment by jgsogo** [comment]
Parece que las URLs al vocabulario son del tipo ```http://qudt.org/vocab/unit#pound```.
