### ISSUE TITLE
Server Error 500 Django

### ISSUE THREAD

**Issue by irenecordoba** [jgsogo/muia-linkeddata#23]
Al acceder como administrador a:
* http://rafco.jgsogo.es/admin/diseases/allergencausesdisease/ 
* http://rafco.jgsogo.es/admin/diseases/foodcausesdisease/
* http://rafco.jgsogo.es/admin/diseases/nutrientcausesdisease/

Opinión de @alfhonso: puede ser Javier que los TXTs no estén todos OK en la carga realizada en rafco.jgsogo.es? Es decir, hicimos el último cambio quitando espacios a las Diseases, y cambié también los xxxCausesDiases.txt. Ese error es que el archivo correspondiente no existe? Lo vemos.

**Comment by jgsogo** [comment]
Done! Sólo había que reiniciar el servidor para que cargara algunos cambios.
