### ISSUE TITLE
Elaborar queries de SPARQL

### ISSUE THREAD

**Issue by jgsogo** [jgsogo/muia-linkeddata#24]
Hay que hacer algunas queries de sparql para lanzarlas contra nuestro endpoint... si incluyen linking ya sería la repera.

**Comment by irenecordoba** [comment]
Porque tengamos alguna he diseñado esta:

    PREFIX rafco: <http://rafco.jgsogo.es/datosabiertos/def/rafco#>

    SELECT DISTINCT ?nutr ?shrtDesc ?sciName
    {
       ?food a rafco:Food.
       ?nutrient a rafco:Nutrient.

       ?food rafco:longDesc ?desc;
                 rafco:shrtDesc ?shrtDesc;
                 rafco:sciName ?sciName
            FILTER(regex(?desc, "tomato")).

       ?food rafco:nutrientwithamount ?x.
       ?x rafco:nutrient ?nutrient.
       ?nutrient rafco:description ?nutr.
    }

    ORDER BY (?sciName)

Deberían dar los nutrientes de los Food que contengan "Tomato", ordenados por el nutriente. ¿Alguien puede depurarla?

**Comment by irenecordoba** [comment]
PD: Si no la intentaré depurar yo mañana por la tarde... pero no prometo nada porque tengo el día ya bastante liado así que @alfhonso si pudieras echar una mano con esto lo agradecería

**Comment by irenecordoba** [comment]
Hola de nuevo,

No he conseguido que me funcione la query, dejan de aparecer resultados en cuanto intento sacar el nutrient de un NutrientWithAmount. He hecho otra para ver cuantas propiedades salían de cada NutrientWithAmount y no me salía ninguna (?). Esta sí me funciona:

    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

    SELECT DISTINCT ?shrtDesc ?food
    WHERE {
    ?item rdf:type spec:Food .

    ?item spec:longDesc ?food ;
             spec:shrtDesc ?shrtDesc;
             FILTER(regex(?food, "tomato")).
    } 

    ORDER BY (?food)

Así que así tenemos al menos una.

**Comment by jgsogo** [comment]
No se por qué, pero no están importándose todas las tripletas... estoy corriendo el script de importación una y otra a ver si van añadiéndose cosas... a lo mejor lo de que sean 700Mb no ayuda mucho ;D

**Comment by jgsogo** [comment]
Este cambio nos da la vida: f2fc5a0c1f05a7620a9d9407f638ab63981d2aad Ahora ya se pueden hacer queries como dios manda.

**Comment by irenecordoba** [comment]
¡¡¡¡ Ha funcionado a la primera !!! :D Os la dejo aquí con el sciName quitado porque no hay casi y queda mal tantos vacíos, y añadido el amount para que salga algo más. El filter de amount 0 es necesario.

** Nutrientes y su respectiva cantidad de las comidas que llevan tomate, ordenados y agrupados por comida **

    PREFIX rafco: <http://rafco.jgsogo.es/datosabiertos/def/rafco#>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

    SELECT DISTINCT ?shrtDesc  ?nutr ?amount
    {
       ?food rdf:type rafco:Food.
       ?nutrient rdf:type rafco:Nutrient.

       ?food rafco:longDesc ?desc;
                 rafco:shrtDesc ?shrtDesc
            FILTER(regex(?desc, "tomato")).

       ?food rafco:nutrientWithAmount ?x.
       ?x rafco:nutrient ?nutrient.
       ?x rafco:amount ?amount
            FILTER(?amount > 0).
       ?nutrient rafco:description ?nutr.
    }

    GROUP BY (?shrtDesc)
    ORDER BY (?shrtDesc)

Mejor ponemos esta mañana en la demo que es más elaborada :) o podemos hacerlo incremental, primero enseñamos las comidas con tomate y luego enseñamos esta.

Aupa!

**Comment by jgsogo** [comment]
Actualizado! Y añado una query más que creo que es interesante (encaja con
las competence-questions que teníamos):

Recetas que utilicen "cayenn" AND "carrots" <- se puede cambiar por otras
cosas.

@alfonso, a la tuya le tuve que quitar un punto y coma...

http://rafco.jgsogo.es/about/

**Comment by irenecordoba** [comment]
@jgsogo He visto que tanto en la mía como en la tuya no se han copiado bien los prefijos en el about. También el título de la mía se te ha pasado actualizarlo. Sería:

**Nutrients and their amount on the different foods containing tomato**

**Comment by jgsogo** [comment]
que asco de html... que hay que "escapar" los simbolitos "<" y ">". Done, i
think!

2015-01-13 12:15 GMT+01:00 Irene Córdoba Sánchez <notifications@github.com>:

**Comment by irenecordoba** [comment]
jajaja si, yo ya lo veo perfecto :)

**Comment by jgsogo** [comment]
Creo que con 3 de ejemplo en el "about" es suficiente ;D
