### ISSUE TITLE
Organización presentaciones

### ISSUE THREAD

**Issue by irenecordoba** [jgsogo/muia-linkeddata#26]
He visto que @alfhonso ha subido un pptx, creo que con algunos de los esquemas que tenemos en el .doc. Deberíamos hacer algún esquema de presentación y repartirnoslo para que cada uno hagamos las transparencias de la parte que vayamos a exponer durante el día de mañana.

**Comment by jgsogo** [comment]
Por mí, este esquema:

1) Ontología

 * recursos ajenos utilizados
 * grafo foods
 * grafo recipes
 * grafo allergens/diseases

2) Linked Data

 * Origen de los datos + LICENCIAS
 * ETL
 * Deploy en servidor

3) Demo

 * IRIs
 * Sparql

**Comment by irenecordoba** [comment]
A la ontología le deberíamos dedicar más tiempo, porque cuenta más que la aplicación de Linked Data (35% y 25% respectivamente). El punto 1 por tanto lo dividiría en:


1) Ontología

 * requisitos
 * recursos ontológicos reutilizados
 * recursos no ontológicos reutilizados
 * grafo foods
 * grafo recipes
 * grafo allergens/diseases
 * evaluación con oops

En cuanto a cantidad de transparencias, ¿en algún lado dice cuánto tiempo vamos a estar cada grupo? Porque en función de eso serán más o menos.

**Comment by irenecordoba** [comment]
Y otra cosa, también es importante saber si vamos a presentar cada grupo su ontología y después el Linked Data, o todo junto, para organizar la presentación. Le mandaré un correo a Óscar a ver si hay suerte y me responde hoy

**Comment by irenecordoba** [comment]
Os acabo de reenviar la contestación de Óscar. En base a ello nos quedamos entonces con la propuesta de Javier. Por hacer un reparto simple, qué os parece:

1) Irene, 2) Alfonso, 3) Javier. Y cada uno 5 minutos de charla, con lo que llenamos los 5 minutos que dice él.

**Comment by irenecordoba** [comment]
1) Irene 
2) Javier 
3) Alfonso

5 mins por persona
