### ISSUE TITLE
Cómo expresar los tiempos

### ISSUE THREAD

**Issue by jgsogo** [jgsogo/muia-linkeddata#3]
Alfonso, tu idea sobre cómo expresar las magnitudes temporales se perdió en la maraña de emails... ¿puedes encontrarlo y ponerlo por aquí? Quedará más organizado... 

Recuerdo que en la ontología pusimos que esos tiempos serían instancias de time:DurationDescription (time: http://www.w3.org/TR/owl-time/)

**Comment by alfhonso** [comment]
Creo que con lo dicho podemos cerrar esta Issue.
