### ISSUE TITLE
Listado de IRIs: Ontología

### ISSUE THREAD

**Issue by irenecordoba** [jgsogo/muia-linkeddata#6]
Abro esto para escribir las IRIs que tenemos por ahora en los R2RML **para la ontología**. Si tenéis que crear nuevas en otros contextos seguid el formato que he puesto en otro issue ya cerrado, esto es para llevar la cuenta. Cuando creéis otras ponedlas aquí para que actualice la lista.

**Food**
*Conceptos*
* http://rafco.jgsogo.es/linkeddata/def/rafco#Food
* http://rafco.jgsogo.es/linkeddata/def/rafco#NutrientWithAmount
* http://rafco.jgsogo.es/linkeddata/def/rafco#WeightPerAmount
* http://rafco.jgsogo.es/linkeddata/def/rafco#Langual

*Propiedades*
* http://rafco.jgsogo.es/linkeddata/def/rafco#longDesc
* http://rafco.jgsogo.es/linkeddata/def/rafco#shrtDesc
* http://rafco.jgsogo.es/linkeddata/def/rafco#sciName
* http://rafco.jgsogo.es/linkeddata/def/rafco#nutrientWithAmount
* http://rafco.jgsogo.es/linkeddata/def/rafco#nutrient
* http://rafco.jgsogo.es/linkeddata/def/rafco#amount
* http://rafco.jgsogo.es/linkeddata/def/rafco#langual
* http://rafco.jgsogo.es/linkeddata/def/rafco#weightPerAmount
* http://rafco.jgsogo.es/linkeddata/def/rafco#foodAmount
* http://rafco.jgsogo.es/linkeddata/def/rafco#gramWeight
* http://rafco.jgsogo.es/linkeddata/def/rafco#msreDesc
* http://rafco.jgsogo.es/linkeddata/def/rafco#description

**Disease**
*Conceptos*
* http://rafco.jgsogo.es/linkeddata/def/rafco#Disease

*Propiedades*
* http://rafco.jgsogo.es/linkeddata/def/rafco#doid
* http://rafco.jgsogo.es/linkeddata/def/rafco#causes

**Nutrient**
*Conceptos*
* http://rafco.jgsogo.es/linkeddata/def/rafco#Nutrient

*Propiedades*
* http://rafco.jgsogo.es/linkeddata/def/rafco#type
* http://rafco.jgsogo.es/linkeddata/def/rafco#main
* http://rafco.jgsogo.es/linkeddata/def/rafco#tagname
* http://rafco.jgsogo.es/linkeddata/def/rafco#numDec
* http://rafco.jgsogo.es/linkeddata/def/rafco#units

**Allergen**
*Conceptos*
* http://rafco.jgsogo.es/linkeddata/def/rafco#Allergen

*Propiedades*
* http://rafco.jgsogo.es/linkeddata/def/rafco#group
* http://rafco.jgsogo.es/linkeddata/def/rafco#main
* http://rafco.jgsogo.es/linkeddata/def/rafco#type
* http://rafco.jgsogo.es/linkeddata/def/rafco#species
* http://rafco.jgsogo.es/linkeddata/def/rafco#common
* http://rafco.jgsogo.es/linkeddata/def/rafco#iuis

**Recipes**
*Conceptos*
* http://rafco.jgsogo.es/linkeddata/def/rafco#Ingredient
* http://rafco.jgsogo.es/linkeddata/def/rafco#Recipe
* http://rafco.jgsogo.es/linkeddata/def/rafco#IngredientWithAmount

*Propiedades*
* http://rafco.jgsogo.es/linkeddata/def/rafco#isProduced
* http://rafco.jgsogo.es/linkeddata/def/rafco#produces
* http://rafco.jgsogo.es/linkeddata/def/rafco#hasTitle
* http://rafco.jgsogo.es/linkeddata/def/rafco#hasRating
* http://rafco.jgsogo.es/linkeddata/def/rafco#recipeYields
* http://rafco.jgsogo.es/linkeddata/def/rafco#cookTime
* http://rafco.jgsogo.es/linkeddata/def/rafco#prepTime
* http://rafco.jgsogo.es/linkeddata/def/rafco#seeAlso
* http://rafco.jgsogo.es/linkeddata/def/rafco#hasImage
* http://rafco.jgsogo.es/linkeddata/def/rafco#hasInstructions
* http://rafco.jgsogo.es/linkeddata/def/rafco#hasText
* http://rafco.jgsogo.es/linkeddata/def/rafco#hasIngredientWithAmount
* http://rafco.jgsogo.es/linkeddata/def/rafco#hasIngredient
* http://rafco.jgsogo.es/linkeddata/def/rafco#value
* http://rafco.jgsogo.es/linkeddata/def/rafco#unit

**Comment by irenecordoba** [comment]
Una cosa que no sería muy difícil de añadir que nos hemos saltado en los R2RML es la relación `partOf` de `Nutrient` a `Food` que pusimos en la ontología. ¿La añado o lo dejamos como está? Hay otra similar que es la de `Nutrient hasRole Allergen` pero esta es más difícil porque creo que no lo tenemos expresado en los datos, ¿no es así @alfhonso?

**Comment by alfhonso** [comment]
No la hemos expresado. Creo que una manera sería con un nuevo campo que enlazara a los Nutrients que quisiéramos con el PK del Allergen. Aunque en la teoría está muy bien, en la práctica no, porque hay pocos casos: Lactosa, Fructosa, Galactosa. Yo lo dejaría sin aplicar.

La mayoría de los alergenos son proteinas específicas, pero las proteinas no se separan en los nutrientes. Se consideran un único grupo. Así que no hay una relación uno a uno clara.

**Comment by irenecordoba** [comment]
Ok a future work que va xD.

**Comment by irenecordoba** [comment]
Pendiente de probar el juntar `foodCauses`, `nutrientCauses` y `allergenCauses` en una única propiedad `causes` cuando se arregle #22

**Comment by irenecordoba** [comment]
Información trasladada al documento a la parte correspondiente para cuando se redacte. IRIs definitivas, ya no habrá más cambios por mi parte en los R2RML o la ontología a no ser que surja algo gravísimo.
