### ISSUE TITLE
Ontology outdated 

### ISSUE THREAD

**Issue by irenecordoba** [jgsogo/muia-linkeddata#9]
En la ontología una parte muy importante era la de household units. Sin embargo, esto en la aplicación de Linked Data por ahora solamente está traducido en los elementos que se han convertido de la tabla WEIGHTS.txt de la USDA. ¿Es esto suficiente aunque no abarque toda la ontología?. En el caso de Food, sí, no estoy tan segura en el caso de Recipes y el manejo de ingredientes, confírmame @jgsogo.

Independientemente de eso, ¿queréis reutilizar más elementos de esa parte de la ontología? Si es así creo que habría que modificar los datos, su importación y los R2RML. Así que quizá para seguir avanzando si es suficiente en ambos casos mejor dejarlo como está, ¿no?

**Comment by irenecordoba** [comment]
@alfhonso en los datos de Nutrient aparecen dos campos `main` y `type`, que no tuvimos en cuenta en la ontología. ¿A qué tipo de datos deberían ir?

**Comment by irenecordoba** [comment]
@jgsogo el campo msreDesc en el R2RML de food creo que debería ser un `QUDT:NotUsedWithSIUnit`, como con las recetas. ¿Cambiarlo a eso es un lío ahora o se puede hacer?

**Comment by jgsogo** [comment]
No me he metido a mirar los R2RML de food y demás, tan sólo me preocupé de que funcionaran. Se puede cambiar absolutamente todo, sin problemas (a partir de los R2RML) <- y si hay alguna cosa que tiene que estar en la BD del Virtuoso sí o sí se avisa para que la vuelva a reconstruir.

Lo único que pediría que no se tocara mucho (si no es por alguna necesidad mayor) es el MySQL.

**Comment by irenecordoba** [comment]
Muy bien, sabiendo eso meteré entonces algunos cambios en los R2RML que he puesto en Future Work y que son una chorrada. Cuando los pruebe los subo, mientras tanto subo la versión de la ontología que está de acuerdo a los R2RML que tenemos ahora exceptuando algunas preguntas que me quedan por resolver.

La última duda de esta parte @jgsogo, `hasRating` no estaba antes, he puesto como Range un `int`, ¿es correcto, o tiene que ser float o unsigned u otro formato?

**Comment by jgsogo** [comment]
float/double, que hay "medias" estrellas en las valoraciones.
